service: mybackend

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x


functions:
  todos:
    handler: handler.getTodos
    events:
      - http:
          path: todos
          method: get
          cors: true